2025-04-20 14:18:01,381 INFO    MainThread:1273042 [wandb_setup.py:_flush():76] Configure stats pid to 1273042
2025-04-20 14:18:01,382 INFO    MainThread:1273042 [wandb_setup.py:_flush():76] Loading settings from /home/md5121/.config/wandb/settings
2025-04-20 14:18:01,382 INFO    MainThread:1273042 [wandb_setup.py:_flush():76] Loading settings from /scratch/md5121/okhatisathi/tacotron2/wandb/settings
2025-04-20 14:18:01,382 INFO    MainThread:1273042 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-04-20 14:18:01,382 INFO    MainThread:1273042 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-04-20 14:18:01,382 INFO    MainThread:1273042 [wandb_init.py:_log_setup():461] Logging user logs to /scratch/md5121/okhatisathi/tacotron2/wandb/run-20250420_141801-yudt0ivs/logs/debug.log
2025-04-20 14:18:01,382 INFO    MainThread:1273042 [wandb_init.py:_log_setup():462] Logging internal logs to /scratch/md5121/okhatisathi/tacotron2/wandb/run-20250420_141801-yudt0ivs/logs/debug-internal.log
2025-04-20 14:18:01,382 INFO    MainThread:1273042 [wandb_init.py:_jupyter_setup():411] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x1554a1c70390>
2025-04-20 14:18:01,383 INFO    MainThread:1273042 [wandb_init.py:init():495] calling init triggers
2025-04-20 14:18:01,384 INFO    MainThread:1273042 [wandb_init.py:init():499] wandb.init called with sweep_config: {}
config: {}
2025-04-20 14:18:01,384 INFO    MainThread:1273042 [wandb_init.py:init():548] starting backend
2025-04-20 14:18:01,384 INFO    MainThread:1273042 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-20 14:18:01,385 INFO    MainThread:1273042 [backend.py:ensure_launched():217] starting backend process...
2025-04-20 14:18:01,454 INFO    MainThread:1273042 [backend.py:ensure_launched():222] started backend process with pid: 1342050
2025-04-20 14:18:01,472 INFO    MainThread:1273042 [wandb_init.py:init():558] backend started and connected
2025-04-20 14:18:01,495 INFO    MainThread:1273042 [wandb_run.py:_label_probe_notebook():1084] probe notebook
2025-04-20 14:18:01,495 INFO    MainThread:1273042 [wandb_run.py:_label_probe_notebook():1094] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-04-20 14:18:01,495 INFO    MainThread:1273042 [wandb_init.py:init():634] updated telemetry
2025-04-20 14:18:01,676 INFO    MainThread:1273042 [wandb_init.py:init():666] communicating run to backend with 30 second timeout
2025-04-20 14:18:03,806 INFO    MainThread:1273042 [wandb_run.py:_on_init():1919] communicating current version
2025-04-20 14:18:03,888 INFO    MainThread:1273042 [wandb_run.py:_on_init():1923] got version response upgrade_message: "wandb version 0.19.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-04-20 14:18:03,888 INFO    MainThread:1273042 [wandb_init.py:init():700] starting run threads in backend
2025-04-20 14:18:07,695 INFO    MainThread:1273042 [wandb_run.py:_console_start():1893] atexit reg
2025-04-20 14:18:07,696 INFO    MainThread:1273042 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.WRAP
2025-04-20 14:18:07,699 INFO    MainThread:1273042 [wandb_run.py:_redirect():1803] Wrapping output streams.
2025-04-20 14:18:07,704 INFO    MainThread:1273042 [wandb_run.py:_redirect():1827] Redirects installed.
2025-04-20 14:18:07,704 INFO    MainThread:1273042 [wandb_init.py:init():732] run started, returning control to user process
2025-04-20 14:18:09,863 INFO    MainThread:1273042 [wandb_run.py:_finish():1680] finishing run md5121-new-york-university/tacotron2/yudt0ivs
2025-04-20 14:18:09,864 INFO    MainThread:1273042 [jupyter.py:save_history():435] not saving jupyter history
2025-04-20 14:18:09,864 INFO    MainThread:1273042 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2025-04-20 14:18:09,864 INFO    MainThread:1273042 [wandb_init.py:_jupyter_teardown():393] cleaning up jupyter logic
2025-04-20 14:18:09,867 INFO    MainThread:1273042 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2025-04-20 14:18:09,889 INFO    MainThread:1273042 [wandb_run.py:_restore():1834] restore
